source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
use_frameworks!

pod 'Alamofire'
pod 'SwiftyJSON', :git => 'https://github.com/SwiftyJSON/SwiftyJSON.git'
pod 'Colours'
pod 'MBProgressHUD'
pod 'SnapKit'
pod 'DateTools'
pod 'SVPullToRefresh'
pod 'DTCoreText', :git => 'https://github.com/davbeck/DTCoreText.git'
pod 'REMenu'
pod 'NYXImagesKit'
pod 'UIImage+Additions'
pod 'UIImage-Helpers'
pod 'TMCache'
pod 'TSMessages', git: 'https://github.com/KrauseFx/TSMessages.git', commit: '7ef3990de3c626e8f3e50bfabb53f76997e374ce'
pod 'ReachabilitySwift', git: 'https://github.com/ashleymills/Reachability.swift'